from contextlib import AbstractContextManager
from typing import Any, Protocol

Record = dict[str, Any]


class RecordRepository(Protocol):
    def transaction(self) -> AbstractContextManager["RecordRepository"]: ...

    def create(self, project: str, kind: str, data: dict, record_id: str | None = None) -> str: ...

    def get(
        self, record_id: str, project: str | None = None, *, lock: bool = False, kind: str | None = None
    ) -> Record: ...

    def save(self, record_id: str, data: dict, revision: int | None = None) -> None: ...

    def latest(self, project: str, kind: str) -> Record | None: ...

    def get_request(self, project: str, request_key: str) -> Record | None: ...

    def add_request(self, project: str, request_key: str, fingerprint: str, record_id: str) -> None: ...

    def lock_request(self, value: str) -> None: ...

    def pending_job_ids(self) -> list[str]: ...

    def delete_run_checkpoints(self, run_id: str) -> None: ...

    def delete_record(self, record_id: str, project: str, kind: str) -> None: ...

    def public(self, row: Record) -> dict: ...

    def ready(self) -> tuple[bool, str]: ...
